// Sector and region baselines from the VERIS Community Database (VCDB, CC BY-SA 4.0), for step 6
// of docs/backend-plan.md. Writes SQL to stdout or --out; apply with
//   npx supabase db query --linked -f <file>
//
// For each sector and region, how much more or less often each attack type shows up in its
// incidents than in all incidents (the "lift"). Sector and region scores weight the six global
// sub-index scores by these lifts. VCDB is updated a few times a year and has few incidents after
// 2021, so years are pooled; MOVEit (one campaign entered as ~750 incidents in 2023) is left out.
//
//   node scripts/vcdb/index.mjs --out vcdb.sql
import { createWriteStream } from 'node:fs';
import { strFromU8, unzipSync } from 'fflate';

const URL = 'https://raw.githubusercontent.com/vz-risk/VCDB/master/data/joined/vcdb.json.zip';
const FIRST_YEAR = 2010;
/** Pulls small groups towards the overall mix: worth this many incidents of the average. */
const PRIOR = 50;
const MIN_LIFT = 0.5;
const MAX_LIFT = 2;

const out = process.argv.includes('--out') ? createWriteStream(process.argv[process.argv.indexOf('--out') + 1]) : process.stdout;
const log = (...m) => console.error(...m);

const has = (list, value) => Array.isArray(list) && list.includes(value);

/** Which of our six attack types an incident involves. One incident can count for several. */
function vectors(i) {
  const a = i.action ?? {};
  const out = [];
  if (has(a.malware?.variety, 'Ransomware')) out.push('ransomware');
  if (['Exploit vuln', 'Exploit misconfig', 'SQLi'].some((v) => has(a.hacking?.variety, v) || has(a.malware?.variety, v))) {
    out.push('exploitation');
  }
  if (a.social) out.push('phishing');
  if (i.actor?.partner) out.push('supply');
  if (has(a.hacking?.variety, 'DoS')) out.push('ddos');
  if (i.actor?.internal) out.push('insider');
  return out;
}

/** NAICS code to sector; telecom and IT services need more than two digits. */
function sector(naics) {
  const code = String(naics ?? '');
  if (code.startsWith('517')) return 'telecom';
  if (code.startsWith('5415') || code.startsWith('51')) return 'technology';
  const two = code.slice(0, 2);
  return {
    62: 'health', 52: 'finance', 92: 'government', 61: 'education', 44: 'retail', 45: 'retail',
    48: 'transport', 49: 'transport', 31: 'manufacturing', 32: 'manufacturing', 33: 'manufacturing',
    22: 'energy', 21: 'energy',
  }[two] ?? null;
}

/** UN M49 region codes (super-region + sub-region) to our five regions. */
function regions(codes) {
  const out = new Set();
  for (const code of codes ?? []) {
    if (code === '019021' || code.startsWith('021')) out.add('nam');
    else if (code.startsWith('019')) out.add('latam');
    else if (code.startsWith('150')) out.add('europe');
    else if (code.startsWith('002') || code === '142145') out.add('mea');
    else if (code.startsWith('142') || code.startsWith('009')) out.add('apac');
  }
  return [...out];
}

const res = await fetch(URL);
if (!res.ok) throw new Error(`${URL} returned ${res.status}`);
const zip = unzipSync(new Uint8Array(await res.arrayBuffer()));
const incidents = JSON.parse(strFromU8(Object.values(zip)[0]));
log(`${incidents.length} incidents in VCDB`);

const VECTORS = ['ransomware', 'exploitation', 'phishing', 'supply', 'ddos', 'insider'];
const groups = new Map(); // "kind|area" -> { n, counts }
const add = (key, vs) => {
  const g = groups.get(key) ?? { n: 0, counts: Object.fromEntries(VECTORS.map((v) => [v, 0])) };
  g.n++;
  for (const v of vs) g.counts[v]++;
  groups.set(key, g);
};

let used = 0;
for (const i of incidents) {
  if (i.security_incident !== 'Confirmed') continue;
  if ((i.timeline?.incident?.year ?? 0) < FIRST_YEAR) continue;
  if (/moveit/i.test(`${i.summary ?? ''} ${JSON.stringify(i.reference ?? '')}`)) continue;
  const vs = vectors(i);
  if (!vs.length) continue; // none of our six attack types
  used++;
  add('all|all', vs);
  const s = sector(i.victim?.industry);
  if (s) add(`sector|${s}`, vs);
  for (const r of regions(i.victim?.region)) add(`region|${r}`, vs);
}
log(`${used} confirmed incidents since ${FIRST_YEAR} with at least one of our attack types (MOVEit excluded)`);

const all = groups.get('all|all');
const rows = [];
for (const [key, g] of groups) {
  if (key === 'all|all') continue;
  const [kind, area] = key.split('|');
  for (const v of VECTORS) {
    const overall = all.counts[v] / all.n;
    const share = (g.counts[v] + PRIOR * overall) / (g.n + PRIOR);
    const lift = Math.min(MAX_LIFT, Math.max(MIN_LIFT, share / overall));
    rows.push(`('${kind}', '${area}', '${v}', ${lift.toFixed(3)}, ${g.counts[v]}, ${g.n})`);
  }
  log(`${kind} ${area}: ${g.n} incidents`);
}

out.write(`-- Generated by scripts/vcdb/index.mjs on ${new Date().toISOString()} from ${used} VCDB incidents.\n`);
out.write(`insert into public.area_profiles (kind, area, vector, lift, incidents, area_incidents) values\n  ${rows.join(',\n  ')}\n`);
out.write('on conflict (kind, area, vector) do update set lift = excluded.lift, incidents = excluded.incidents,\n');
out.write('  area_incidents = excluded.area_incidents, updated_at = now();\n');
if (out !== process.stdout) out.end();
